// <auto-generated />
using System;
using AspNetCorePostgreSQLDockerApp.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace AspNetCorePostgreSQLDockerApp.Migrations.DockerCommandsDb
{
    [DbContext(typeof(DockerCommandsDbContext))]
    partial class DockerCommandsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("AspNetCorePostgreSQLDockerApp.Models.DockerCommand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Command")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DockerCommands");
                });

            modelBuilder.Entity("AspNetCorePostgreSQLDockerApp.Models.DockerCommandExample", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int?>("DockerCommandId")
                        .HasColumnType("integer");

                    b.Property<string>("Example")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DockerCommandId");

                    b.ToTable("DockerCommandExample");
                });

            modelBuilder.Entity("AspNetCorePostgreSQLDockerApp.Models.DockerCommandExample", b =>
                {
                    b.HasOne("AspNetCorePostgreSQLDockerApp.Models.DockerCommand", null)
                        .WithMany("Examples")
                        .HasForeignKey("DockerCommandId");
                });
#pragma warning restore 612, 618
        }
    }
}
